Import('_default_env')

# SneakyMedia Library

files = Split("""
	AssemblyInfo.cs
    SneakyMedia.cs
    Tag/Tag.cs
	Tag/Scanner.cs
	Tag/ScannerTagLib.cs
	Tag/ScannerXiph.cs
	Tag/Luminescence.Xiph/Enums.cs
	Tag/Luminescence.Xiph/ExtensionMethods.cs
	Tag/Luminescence.Xiph/FlacTagger.cs
	Tag/Luminescence.Xiph/Genre.cs
	Tag/Luminescence.Xiph/ID3PictureFrame.cs
	Tag/Luminescence.Xiph/OggPage.cs
	Tag/Luminescence.Xiph/OggPageReader.cs
	Tag/Luminescence.Xiph/OggTagger.cs
	Tag/Luminescence.Xiph/VorbisComment.cs
	Mount/Mount.cs
	Query/Query.cs
    Query/QueryAv.cs
    Query/QueryBasic.cs
    Query/QueryComms.cs
    Query/QueryCommsTelnet.cs
    Browse/Browse.cs
    Browse/BrowseTelnet.cs
    Browse/BrowseUpnp.cs
    Browse/BrowseWeb.cs
    Query/QueryGeneral.cs
	Engine/Engine.cs
	Database/Database.cs
	Database/DatabaseDb4o.cs
""")

lib = _default_env.CliLibrary('SneakyMedia', files, CLILIBS=['taglib-sharp.dll', 'policy.2.0.taglib-sharp.dll', 'Db4objects.Db4o.dll', 'System.Data.dll'])

# SneakyTagViewer

files = Split("""
	SneakyTagViewer/AssemblyInfo.cs
    SneakyTagViewer/SneakyTagViewer.cs
""")

prog =  _default_env.CliProgram('SneakyTagViewer', files, CLILIBS=['SneakyMedia'])

# SneakyMountViewer

files = Split("""
	SneakyMountViewer/AssemblyInfo.cs
    SneakyMountViewer/SneakyMountViewer.cs
""")

prog += _default_env.CliProgram('SneakyMountViewer', files, CLILIBS=['SneakyMedia'])

# SneakyMediaQuery

files = Split("""
	SneakyMediaQuery/AssemblyInfo.cs
    SneakyMediaQuery/SneakyMediaQuery.cs
""")

prog += _default_env.CliProgram('SneakyMediaQuery', files, CLILIBS=['SneakyMedia'])

Alias('Lib', lib)
Alias('Lib', prog)

Alias('Test', 'Lib')

Default('Test')

