Import('_default_env')


if _default_env['hardware'] == 'Ios':
    SConscript('Linn/Toolkit/Ios/SConscript', exports = ['_default_env'])

elif _default_env['hardware'] == 'Android':
    SConscript('Linn/Toolkit/Droid/SConscript', exports = ['_default_env'])

elif _default_env['hardware'] == 'Windows':
    SConscript('Linn/Toolkit/WinForms/SConscript', exports = ['_default_env'])
    SConscript('Linn/Toolkit/Wpf/SConscript', exports = ['_default_env'])

elif _default_env['hardware'] == 'MacOsX':
    SConscript('Linn/Toolkit/Cocoa/SConscript', exports = ['_default_env'])
    SConscript('Linn/Toolkit/MonoMac/SConscript', exports = ['_default_env'])
    SConscript('Linn/Toolkit/WinForms/SConscript', exports = ['_default_env'])

else:
    SConscript('Linn/Toolkit/WinForms/SConscript', exports = ['_default_env'])


filesRes = Split("""
    Resources/Rss.png
""")
resources = _default_env.Install('$variant_dir/share/Linn/Toolkit', filesRes)
Alias('Resources', resources)

Alias('Lib', resources)
Alias('Test', 'Lib')
Default(['Test','Docs'])

