using Linn;
using System;
using System.Windows;
namespace KinskyDesktopWpf
{

    public class CrashLogDumperForm : ICrashLogDumper
    {
        public CrashLogDumperForm(Window aParent, string aTitle, string aProduct, string aVersion)
        {
            iParent = aParent;
            iTitle = aTitle;
            iProduct = aProduct;
            iVersion = aVersion;
        }

        public void Dump(CrashLog aCrashLog)
        {
            // include some system details in report
            string reportText = aCrashLog.ToString();
            iParent.Dispatcher.Invoke((Action)(() =>
            {
                // show crash form
                CrashLogDialog form = new CrashLogDialog(iTitle, reportText);
                form.Owner = iParent;
                form.ShowDialog();
                if (form.DialogResult.HasValue && form.DialogResult.Value)
                {
                    // post data to Linn
                    DebugReport report = new DebugReport("Crash log generated by " + iProduct + " ver " + iVersion);
                    report.Post(iTitle, reportText);
                }
            }));
            
        }

        private string iTitle;
        private string iProduct;
        private string iVersion;
        private Window iParent;
        //private Icon iIcon;
    }
}