Import('_default_env kVersion')

nib  = _default_env.IbTool('MainMenu.nib', 'MainMenu.xib')
nib += _default_env.IbTool('MainWindow.nib', 'MainWindow.xib')
nib += _default_env.IbTool('ViewAddBookmark.nib', 'ViewAddBookmark.xib')
nib += _default_env.IbTool('ViewBrowserContent.nib', 'ViewBrowserContent.xib')
nib += _default_env.IbTool('ViewSelectionBookmark.nib', 'ViewSelectionBookmark.xib')
nib += _default_env.IbTool('ViewSelectionRoom.nib', 'ViewSelectionRoom.xib')
nib += _default_env.IbTool('ViewSelectionSource.nib', 'ViewSelectionSource.xib')
nib += _default_env.IbTool('WindowAbout.nib', 'WindowAbout.xib')
nib += _default_env.IbTool('WindowPopover.nib', 'WindowPopover.xib')
nib += _default_env.IbTool('WindowUpdate.nib', 'WindowUpdate.xib')
nib  = _default_env.Install('$install_dir/bin/', nib)

SConscript('Monobjc/SConscript', exports = ['_default_env', 'nib', 'kVersion'])

# do sconscript for the updater after everything - this is because the scons node
# for the installer pkg will now exist so dependencies can be correctly set up
SConscript('Installer/SConscript', exports = ['_default_env', 'kVersion'])

