// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KinskyTouch {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ViewWidgetVolumeButtons")]
	public partial class ViewWidgetVolumeButtons {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_buttonDown;
		
		private MonoTouch.UIKit.UIButton __mt_buttonMute;
		
		private MonoTouch.UIKit.UIButton __mt_buttonUp;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonDown")]
		private MonoTouch.UIKit.UIButton buttonDown {
			get {
				this.__mt_buttonDown = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonDown")));
				return this.__mt_buttonDown;
			}
			set {
				this.__mt_buttonDown = value;
				this.SetNativeField("buttonDown", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonMute")]
		private MonoTouch.UIKit.UIButton buttonMute {
			get {
				this.__mt_buttonMute = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonMute")));
				return this.__mt_buttonMute;
			}
			set {
				this.__mt_buttonMute = value;
				this.SetNativeField("buttonMute", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonUp")]
		private MonoTouch.UIKit.UIButton buttonUp {
			get {
				this.__mt_buttonUp = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonUp")));
				return this.__mt_buttonUp;
			}
			set {
				this.__mt_buttonUp = value;
				this.SetNativeField("buttonUp", value);
			}
		}
	}
}
