#!/bin/sh

#> UserLog.nib
#> Plugins

TARGET_DIR=$1/Kinsky.app/Contents/Resources

FILES='../../../External/libmonobjc.2.dylib ../../../Kinsky/Resources/Kinsky2.icns'

echo "Copying files..."
for f in ${FILES}
do
    cp -vf ${f} ${TARGET_DIR}
done
echo "Done copying files"

echo "Copying resources..."
mkdir -v ${TARGET_DIR}/Icons
mkdir -v ${TARGET_DIR}/Images
cp -vf ../../../Layouts/Kinsky/Desktop2/Icons/* ${TARGET_DIR}/Icons
cp -vf ../../../Layouts/Kinsky/Desktop2/Images/* ${TARGET_DIR}/Images
echo "Done copying resources"

echo "Copying plugins..."
cp -vfR $1/Plugins ${TARGET_DIR}
echo "Done copying plugins"

