//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinskyDroid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Album = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AlbumArtError = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Array = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Artist = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int BackButton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int backbuttonfocused = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int backbuttonnormal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int backbuttonpressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Bookmark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int BottomFiller = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int BottomLeftEdge = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int BottomRightEdge = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ButtonBackground = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int buttonfocused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int buttonnormal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int buttonpressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int CD = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ClockIcon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ClockIconElapsed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ClockIconRemaining = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Delete = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int DeleteDown = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Directory = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int DisclosureIndicator = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int EditModeButton = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Error = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int FfwdButton = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Folder = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int FrwdButton = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Home = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int HomeDown = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int HomeOn = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int HourGlass = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int HourGlass2 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Icon = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int LeftFiller = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Library = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int LinnLogo = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int List = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Loading = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Multi = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int MultiDown = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int MultiOn = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int MultiOnDown = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Mute = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int MuteActive = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int MuteIcon = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Pause = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int PauseDown = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int PauseOver = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Play = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int PlayDown = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Playing = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int Playlist = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int PlaylistItem = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int PlaylistSource = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int PlayOver = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int Radio = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int RefreshButton = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int Repeat = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int RepeatButton = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int RepeatButtonForeground = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int RepeatDown = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int RepeatOn = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int RepeatOnDown = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int RightFiller = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int Rocker = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int RockerLeftDown = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int RockerRightDown = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int Room = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int RoomSource = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int Save = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int SaveDown = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int Screws = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int ScrewsLarge = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int Sender = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int SenderNoSend = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int Settings = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int Shuffle = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int ShuffleButton = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int ShuffleButtonForeground = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int ShuffleDown = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int ShuffleOn = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int ShuffleOnDown = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int SkipBack = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int SkipBackDown = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int SkipBackOver = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int SkipForward = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int SkipForwardDown = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int SkipForwardOver = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int Source = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int Standby = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int StandbyButton = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int StandbyButtonForeground = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int StandbyDown = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int StandbyOn = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int StandbyOnDown = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int Stop = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int StopDown = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int StopOver = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int TopBarFiller = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int TopFiller = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int TopLeftEdge = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int TopRightEdge = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int Track = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int TramLines = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int UPNP = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int Video = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int Wheel = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int WheelLarge = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int WheelLargeOver = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int WheelMute = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int WheelOver = 2130837616;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int backbutton = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int bottombar = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int browser = 2131034132;
			
			// aapt resource value: 0x7f050009
			public const int browsercontrols = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int browseritemfirstline = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int browseritemicon = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int browseritemsecondLine = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int deletebutton = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int editmodebutton = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int leftbuttons = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int locationdisplay = 2131034123;
			
			// aapt resource value: 0x7f050013
			public const int middlesection = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int playlist = 2131034133;
			
			// aapt resource value: 0x7f050002
			public const int playnownextlaterbutton = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int repeatbutton = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int rightbuttons = 2131034115;
			
			// aapt resource value: 0x7f05001c
			public const int roomicon = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int roomlist = 2131034139;
			
			// aapt resource value: 0x7f05001e
			public const int roomname = 2131034142;
			
			// aapt resource value: 0x7f05001a
			public const int roomsrefreshbutton = 2131034138;
			
			// aapt resource value: 0x7f050007
			public const int savebutton = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int selectroombutton = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int selectsourcebutton = 2131034136;
			
			// aapt resource value: 0x7f050001
			public const int settingsbutton = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int shufflebutton = 2131034117;
			
			// aapt resource value: 0x7f050021
			public const int sourceicon = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int sourcelist = 2131034144;
			
			// aapt resource value: 0x7f050019
			public const int sourcelisttitle = 2131034137;
			
			// aapt resource value: 0x7f050022
			public const int sourcename = 2131034146;
			
			// aapt resource value: 0x7f05001f
			public const int sourcesrefreshbutton = 2131034143;
			
			// aapt resource value: 0x7f05001d
			public const int standbybutton = 2131034141;
			
			// aapt resource value: 0x7f050011
			public const int topbar = 2131034129;
			
			// aapt resource value: 0x7f050023
			public const int trackartwork = 2131034147;
			
			// aapt resource value: 0x7f05000f
			public const int trackcontrols = 2131034127;
			
			// aapt resource value: 0x7f050024
			public const int trackdisplay1 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int trackdisplay2 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int trackdisplay3 = 2131034150;
			
			// aapt resource value: 0x7f050016
			public const int viewsourceselection = 2131034134;
			
			// aapt resource value: 0x7f050010
			public const int volumeandtransportcontrols = 2131034128;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BottomBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BrowserControls = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BrowserItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RoomAndSourceControls = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RoomList = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RoomListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SourceList = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SourceListItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TrackControls = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int VolumeAndTransportControls = 2130903050;
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040003
			public const int controlsdimensions = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int dividerbackground = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int splitterleft = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int splitterright = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int textviewtext = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int toolbardimensions = 2130968580;
			
			private Style()
			{
			}
		}
	}
}
