using System;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;
using System.Text;

namespace Linn.Toolkit.WinForms
{
    public class CrashLogDumperForm : ICrashLogDumper
    {
        public CrashLogDumperForm(string aTitle, string aProduct, string aVersion, Icon aIcon) {
            iTitle = aTitle;
            iProduct = aProduct;
            iVersion = aVersion;
            iIcon = aIcon;
        }

        public void Dump(CrashLog aCrashLog)
        {
            // include some system details in report
            string reportText = aCrashLog.ToString();
            // show crash form
            FormCrashLogDumper form = new FormCrashLogDumper(iTitle, iIcon, reportText);
            DialogResult result = form.ShowDialog();
            if (result == DialogResult.OK)
            {
                // post data to Linn
                DebugReport report = new DebugReport("Crash log generated by " + iProduct + " ver " + iVersion);
                report.Post(iTitle, reportText);
            }
        }

        private string iTitle;
        private string iProduct;
        private string iVersion;
        private Icon iIcon;
    }
}

