//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linn.Kinsky.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linn.Kinsky.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap BusyIcon {
            get {
                object obj = ResourceManager.GetObject("BusyIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BusyIconElement {
            get {
                object obj = ResourceManager.GetObject("BusyIconElement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DialogBoxBackground {
            get {
                object obj = ResourceManager.GetObject("DialogBoxBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DialogBoxBottomFiller {
            get {
                object obj = ResourceManager.GetObject("DialogBoxBottomFiller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DialogBoxLeftFiller {
            get {
                object obj = ResourceManager.GetObject("DialogBoxLeftFiller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DialogBoxRightFiller {
            get {
                object obj = ResourceManager.GetObject("DialogBoxRightFiller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DialogBoxTopFiller {
            get {
                object obj = ResourceManager.GetObject("DialogBoxTopFiller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DialogBoxWing1 {
            get {
                object obj = ResourceManager.GetObject("DialogBoxWing1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DialogBoxWing2 {
            get {
                object obj = ResourceManager.GetObject("DialogBoxWing2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DialogBoxWing3 {
            get {
                object obj = ResourceManager.GetObject("DialogBoxWing3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DialogBoxWing4 {
            get {
                object obj = ResourceManager.GetObject("DialogBoxWing4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DownArrow {
            get {
                object obj = ResourceManager.GetObject("DownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DownArrowMouse {
            get {
                object obj = ResourceManager.GetObject("DownArrowMouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DownArrowOn {
            get {
                object obj = ResourceManager.GetObject("DownArrowOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DownArrowTouch {
            get {
                object obj = ResourceManager.GetObject("DownArrowTouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconAux {
            get {
                object obj = ResourceManager.GetObject("IconAux", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconAuxSource {
            get {
                object obj = ResourceManager.GetObject("IconAuxSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconCd {
            get {
                object obj = ResourceManager.GetObject("IconCd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconDs {
            get {
                object obj = ResourceManager.GetObject("IconDs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconRadioSource {
            get {
                object obj = ResourceManager.GetObject("IconRadioSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconRoom {
            get {
                object obj = ResourceManager.GetObject("IconRoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconSpdifSource {
            get {
                object obj = ResourceManager.GetObject("IconSpdifSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconTosLinkSource {
            get {
                object obj = ResourceManager.GetObject("IconTosLinkSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconTuner {
            get {
                object obj = ResourceManager.GetObject("IconTuner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconUpnpAv {
            get {
                object obj = ResourceManager.GetObject("IconUpnpAv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap KinskyLogo {
            get {
                object obj = ResourceManager.GetObject("KinskyLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NoAlbumArt {
            get {
                object obj = ResourceManager.GetObject("NoAlbumArt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ThumbMiddle {
            get {
                object obj = ResourceManager.GetObject("ThumbMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ThumbMiddleMouse {
            get {
                object obj = ResourceManager.GetObject("ThumbMiddleMouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ThumbMiddleTouch {
            get {
                object obj = ResourceManager.GetObject("ThumbMiddleTouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap UpArrow {
            get {
                object obj = ResourceManager.GetObject("UpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap UpArrowMouse {
            get {
                object obj = ResourceManager.GetObject("UpArrowMouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap UpArrowOn {
            get {
                object obj = ResourceManager.GetObject("UpArrowOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap UpArrowTouch {
            get {
                object obj = ResourceManager.GetObject("UpArrowTouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowsClose {
            get {
                object obj = ResourceManager.GetObject("WindowsClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowsCloseMouse {
            get {
                object obj = ResourceManager.GetObject("WindowsCloseMouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowsCloseTouch {
            get {
                object obj = ResourceManager.GetObject("WindowsCloseTouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowsMaximize {
            get {
                object obj = ResourceManager.GetObject("WindowsMaximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowsMaximizeMouse {
            get {
                object obj = ResourceManager.GetObject("WindowsMaximizeMouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowsMaximizeTouch {
            get {
                object obj = ResourceManager.GetObject("WindowsMaximizeTouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowsMinimize {
            get {
                object obj = ResourceManager.GetObject("WindowsMinimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowsMinimizeMouse {
            get {
                object obj = ResourceManager.GetObject("WindowsMinimizeMouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowsMinimizeTouch {
            get {
                object obj = ResourceManager.GetObject("WindowsMinimizeTouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowsRestore {
            get {
                object obj = ResourceManager.GetObject("WindowsRestore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowsRestoreMouse {
            get {
                object obj = ResourceManager.GetObject("WindowsRestoreMouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap WindowsRestoreTouch {
            get {
                object obj = ResourceManager.GetObject("WindowsRestoreTouch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
