Import('_default_env')

files = Split("""
    Properties/AssemblyInfo.cs
    Gui/Canvas.cs
    Gui/CanvasGdi.cs
    Gui/Factory.cs
    Gui/Messenger.cs
    Gui/Object.cs
    Gui/Renderer.cs
    Gui/RendererGdi.cs
    Gui/RendererNull.cs
    Gui/Resources/Controller.cs
    Gui/Resources/Message.cs
    Gui/Resources/MessageTranslator.cs
    Gui/Resources/Package.cs
    Gui/Resources/PackageManager.cs
    Gui/Resources/Plugin.cs
    Gui/Resources/Texture.cs
    Gui/Resources/TextureArray.cs
    Gui/Resources/TextureManager.cs
    Gui/SceneGraph/Colour.cs
    Gui/SceneGraph/Node.cs
    Gui/SceneGraph/NodeFont.cs
    Gui/SceneGraph/NodeHit.cs
    Gui/SceneGraph/NodeInput.cs
    Gui/SceneGraph/NodeList.cs
    Gui/SceneGraph/NodePolygon.cs
    Gui/SceneGraph/NodeSlider.cs
    Gui/SceneGraph/NodeText.cs
    Gui/SceneGraph/NodeVolume.cs
    Gui/SceneGraph/RenderState.cs
    Gui/SceneGraph/Srt.cs
    Gui/SceneGraph/Visitor.cs
""")
if _default_env['hardware'] == 'PocketPc':
    files.append('Gui/Resources/Framework/Compact/Texture.cs')
else:
    files.append('Gui/CanvasGdiPlus.cs')
    files.append('Gui/RendererGdiPlus.cs')
    files.append('Gui/Resources/Framework/Full/Texture.cs')
lib = _default_env.CliLibrary('OssGui', files, CLILIBS=['mscorlib', 'System', 'System.Xml', 'OssCore', 'System.Drawing', 'System.Windows.Forms'])
Alias('Lib', lib)

# Legacy Python prototype
# Only kept as Sdp/Preamp use this as the basis for their GUI, when they convert this can be deleted
files = Split("""
    Gui/__init__.py
    Gui/CanvasFrame.py
    Gui/Factory.py
    Gui/Messenger.py
    Gui/Object.py
    Gui/Renderer.py
    Gui/Serialize.py
    Gui/Timer.py
    Gui/XmlStream.py
""")
result = _default_env.Install('$install_dir/lib/Linn/Gui', files)
files = Split("""
    Gui/Resources/__init__.py
    Gui/Resources/Configuration.py
    Gui/Resources/Controller.py
    Gui/Resources/Layout.py
    Gui/Resources/Message.py
    Gui/Resources/MessageTranslator.py
    Gui/Resources/Package.py
    Gui/Resources/Plugin.py
    Gui/Resources/PackageManager.py
    Gui/Resources/TextureManager.py
    Gui/Resources/Texture.py
    Gui/Resources/TextureArray.py
""")
result += _default_env.Install('$install_dir/lib/Linn/Gui/Resources', files)
files = Split("""
    Gui/SceneGraph/__init__.py
    Gui/SceneGraph/Node.py
    Gui/SceneGraph/NodeDiscovery.py
    Gui/SceneGraph/NodeHit.py
    Gui/SceneGraph/NodeInput.py
    Gui/SceneGraph/NodePolygon.py
    Gui/SceneGraph/NodeText.py
    Gui/SceneGraph/RenderState.py
    Gui/SceneGraph/Srt.py
    Gui/SceneGraph/Visitor.py
""")
result += _default_env.Install('$install_dir/lib/Linn/Gui/SceneGraph', files)
result += _default_env.Install('$variant_dir/share/Linn/Gui', 'Gui/Resources/Linn.ico')

Alias('Lib', result)

SConscript('Gui/Test/SConscript', exports = '_default_env')
