//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinskyWeb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinskyWeb.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AboutBox {
            get {
                object obj = ResourceManager.GetObject("AboutBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Common_CSS_jquery_contextmenu_css {
            get {
                object obj = ResourceManager.GetObject("Common/CSS/jquery.contextmenu.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_core_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/core.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_jquery_1_4_2_min_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/jquery-1.4.2.min.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_jquery_contextmenu_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/jquery.contextmenu.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_jquery_json_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/jquery.json.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_jquery_jsonrequest_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/jquery.jsonrequest.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_jquery_selectboxes_min_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/jquery.selectboxes.min.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_jquery_timer_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/jquery.timer.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_jquery_ui_1_8rc3_custom_min_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/jquery-ui-1.8rc3.custom.min.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_jquery_xml2json_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/jquery.xml2json.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_prototype_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/prototype.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_splitpane_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/splitpane.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_Breadcrumb_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/Breadcrumb.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_BreadcrumbMobile_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/BreadcrumbMobile.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_Browser_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/Browser.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_MediaTime_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/MediaTime.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_MediaTimeMobile_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/MediaTimeMobile.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_Playlist_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/Playlist.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_PlayMode_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/PlayMode.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_RoomSelector_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/RoomSelector.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_RoomSelectorMobile_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/RoomSelectorMobile.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_SourceSelector_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/SourceSelector.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_SourceSelectorMobile_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/SourceSelectorMobile.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_StandbyButton_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/StandbyButton.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_Track_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/Track.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_TransportControl_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/TransportControl.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_UpDirectory_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/UpDirectory.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_VolumeControl_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/VolumeControl.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_VolumeControlMobile_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/VolumeControlMobile.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_WasteBin_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/WasteBin.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_Widget_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/Widget.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Scripts_Widgets_WidgetContainer_js {
            get {
                object obj = ResourceManager.GetObject("Common/Scripts/Widgets/WidgetContainer.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Themes_ui_darkness_images_ui_bg_flat_30_cccccc_40x100_png {
            get {
                object obj = ResourceManager.GetObject("Common/Themes/ui-darkness/images/ui-bg_flat_30_cccccc_40x100.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Themes_ui_darkness_images_ui_bg_flat_50_5c5c5c_40x100_png {
            get {
                object obj = ResourceManager.GetObject("Common/Themes/ui-darkness/images/ui-bg_flat_50_5c5c5c_40x100.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Themes_ui_darkness_images_ui_bg_glass_20_555555_1x400_png {
            get {
                object obj = ResourceManager.GetObject("Common/Themes/ui-darkness/images/ui-bg_glass_20_555555_1x400.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Themes_ui_darkness_images_ui_bg_glass_40_0078a3_1x400_png {
            get {
                object obj = ResourceManager.GetObject("Common/Themes/ui-darkness/images/ui-bg_glass_40_0078a3_1x400.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Themes_ui_darkness_images_ui_bg_glass_40_ffc73d_1x400_png {
            get {
                object obj = ResourceManager.GetObject("Common/Themes/ui-darkness/images/ui-bg_glass_40_ffc73d_1x400.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Themes_ui_darkness_images_ui_bg_gloss_wave_25_333333_500x100_png {
            get {
                object obj = ResourceManager.GetObject("Common/Themes/ui-darkness/images/ui-bg_gloss-wave_25_333333_500x100.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Themes_ui_darkness_images_ui_bg_highlight_soft_80_eeeeee_1x100_png {
            get {
                object obj = ResourceManager.GetObject("Common/Themes/ui-darkness/images/ui-bg_highlight-soft_80_eeeeee_1x100.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Themes_ui_darkness_images_ui_bg_inset_soft_25_000000_1x100_png {
            get {
                object obj = ResourceManager.GetObject("Common/Themes/ui-darkness/images/ui-bg_inset-soft_25_000000_1x100.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Themes_ui_darkness_images_ui_bg_inset_soft_30_f58400_1x100_png {
            get {
                object obj = ResourceManager.GetObject("Common/Themes/ui-darkness/images/ui-bg_inset-soft_30_f58400_1x100.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Common_Themes_ui_darkness_jquery_ui_1_8rc3_custom_css {
            get {
                object obj = ResourceManager.GetObject("Common/Themes/ui-darkness/jquery-ui-1.8rc3.custom.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KinskyLogo {
            get {
                object obj = ResourceManager.GetObject("KinskyLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_kinsky_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/kinsky.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_kinsky_ie7_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/kinsky_ie7.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_Widgets_Breadcrumb_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/Widgets/Breadcrumb.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_Widgets_Browser_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/Widgets/Browser.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_Widgets_MediaTime_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/Widgets/MediaTime.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_Widgets_PlayMode_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/Widgets/PlayMode.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_Widgets_RoomSelector_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/Widgets/RoomSelector.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_Widgets_SourceSelector_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/Widgets/SourceSelector.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_Widgets_StandbyButton_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/Widgets/StandbyButton.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_Widgets_Track_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/Widgets/Track.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_Widgets_TransportControl_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/Widgets/TransportControl.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_Widgets_UpDirectory_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/Widgets/UpDirectory.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_Widgets_VolumeControl_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/Widgets/VolumeControl.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_CSS_Widgets_WasteBin_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/CSS/Widgets/WasteBin.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_ajax_loader_gif {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/ajax-loader.gif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Logo_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Logo.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_3kArray_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/3kArray.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Album_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Album.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_AlbumError_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/AlbumError.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Artist_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Artist.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Bin_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Bin.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_BinMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/BinMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Directory_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Directory.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Error_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Error.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Folder_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Folder.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Library_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Library.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_NextPage_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/NextPage.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_NextPageMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/NextPageMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_NoAlbumArt_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/NoAlbumArt.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Pause_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Pause.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_PauseMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/PauseMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_PauseTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/PauseTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Play_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Play.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Playing_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Playing.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Playlist_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Playlist.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_PlayMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/PlayMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_PlayTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/PlayTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_PreviousPage_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/PreviousPage.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_PreviousPageMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/PreviousPageMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Radio_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Radio.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Repeat_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Repeat.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_RepeatActive_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/RepeatActive.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_RepeatActiveMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/RepeatActiveMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_RepeatMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/RepeatMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Shuffle_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Shuffle.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_ShuffleActive_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/ShuffleActive.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_ShuffleActiveMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/ShuffleActiveMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_ShuffleMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/ShuffleMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_SkipBack_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/SkipBack.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_SkipBackMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/SkipBackMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_SkipBackTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/SkipBackTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_SkipForward_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/SkipForward.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_SkipForwardMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/SkipForwardMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_SkipForwardTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/SkipForwardTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Standby_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Standby.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_StandbyActive_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/StandbyActive.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_StandbyActiveMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/StandbyActiveMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Stop_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Stop.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_StopMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/StopMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_StopTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/StopTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Track_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Track.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_UpDirectory_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/UpDirectory.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_UpDirectoryMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/UpDirectoryMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Video_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Video.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_VolumeControl_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/VolumeControl.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_Wheel_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/Wheel.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_WheelInnerGlow_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/WheelInnerGlow.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_WheelSkipBack_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/WheelSkipBack.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_WheelSkipBackMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/WheelSkipBackMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_WheelSkipBackTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/WheelSkipBackTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_WheelSkipForward_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/WheelSkipForward.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_WheelSkipForwardMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/WheelSkipForwardMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_WheelSkipForwardTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/WheelSkipForwardTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_WheelVolumeDown_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/WheelVolumeDown.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_WheelVolumeDownMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/WheelVolumeDownMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_WheelVolumeDownTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/WheelVolumeDownTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_WheelVolumeUp_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/WheelVolumeUp.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_WheelVolumeUpMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/WheelVolumeUpMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Images_Widgets_WheelVolumeUpTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Images/Widgets/WheelVolumeUpTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_kinsky_html {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/kinsky.html", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Desktop_Scripts_kinsky_js {
            get {
                object obj = ResourceManager.GetObject("Layouts/Desktop/Scripts/kinsky.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_kinsky_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/kinsky.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_kinsky_ie7_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/kinsky_ie7.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_Widgets_Breadcrumb_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/Widgets/Breadcrumb.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_Widgets_Browser_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/Widgets/Browser.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_Widgets_MediaTime_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/Widgets/MediaTime.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_Widgets_PlayMode_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/Widgets/PlayMode.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_Widgets_RoomSelector_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/Widgets/RoomSelector.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_Widgets_SourceSelector_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/Widgets/SourceSelector.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_Widgets_StandbyButton_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/Widgets/StandbyButton.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_Widgets_Track_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/Widgets/Track.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_Widgets_TransportControl_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/Widgets/TransportControl.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_Widgets_UpDirectory_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/Widgets/UpDirectory.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_Widgets_VolumeControl_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/Widgets/VolumeControl.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_CSS_Widgets_WasteBin_css {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/CSS/Widgets/WasteBin.css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_ajax_loader_gif {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/ajax-loader.gif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Glass_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Glass.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Logo_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Logo.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_nav_divider_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/nav_divider.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_nav_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/nav.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_3kArray_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/3kArray.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Album_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Album.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_AlbumError_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/AlbumError.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Artist_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Artist.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_AuxSource_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/AuxSource.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Bin_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Bin.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_BinMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/BinMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_CD_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/CD.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Directory_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Directory.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_DS_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/DS.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Error_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Error.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Folder_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Folder.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Home_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Home.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_HomeMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/HomeMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_IconSelectedServer_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/IconSelectedServer.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Library_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Library.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_NextPage_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/NextPage.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_NextPageMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/NextPageMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_NoAlbumArt_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/NoAlbumArt.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Pause_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Pause.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_PauseMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/PauseMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_PauseTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/PauseTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Play_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Play.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Playing_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Playing.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Playlist_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Playlist.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_PlayMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/PlayMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_PlayTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/PlayTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_PreviousPage_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/PreviousPage.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_PreviousPageMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/PreviousPageMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Radio_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Radio.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Repeat_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Repeat.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_RepeatActive_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/RepeatActive.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_RepeatActiveMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/RepeatActiveMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_RepeatMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/RepeatMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Room_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Room.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Shuffle_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Shuffle.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_ShuffleActive_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/ShuffleActive.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_ShuffleActiveMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/ShuffleActiveMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_ShuffleMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/ShuffleMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_SkipBack_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/SkipBack.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_SkipBackMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/SkipBackMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_SkipBackTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/SkipBackTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_SkipForward_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/SkipForward.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_SkipForwardMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/SkipForwardMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_SkipForwardTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/SkipForwardTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Spdif_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Spdif.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Standby_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Standby.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_StandbyActive_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/StandbyActive.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_StandbyActiveMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/StandbyActiveMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Stop_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Stop.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_StopMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/StopMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_StopTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/StopTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_TosLink_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/TosLink.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Track_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Track.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_UpDirectory_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/UpDirectory.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_UpDirectoryMouse_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/UpDirectoryMouse.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_UPNP_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/UPNP.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_Video_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/Video.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_VolumeDown_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/VolumeDown.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_VolumeDownTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/VolumeDownTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_VolumeEmpty_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/VolumeEmpty.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_VolumeUp_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/VolumeUp.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Images_Widgets_VolumeUpTouch_png {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Images/Widgets/VolumeUpTouch.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_kinsky_html {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/kinsky.html", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts_Portrait_Medium_Scripts_kinsky_js {
            get {
                object obj = ResourceManager.GetObject("Layouts/Portrait/Medium/Scripts/kinsky.js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Watermark {
            get {
                object obj = ResourceManager.GetObject("Watermark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
