Import('_default_env')

SConscript('Linn/SConscript', exports = '_default_env')
if _default_env['hardware'] != 'PocketPc':
    SConscript('KinskyEd/SConscript', exports = '_default_env')
    SConscript('Scripts/SConscript', exports = '_default_env')

Alias('Test', 'Lib')

Default('Test')
