Import('_default_env')

import BuildInfo

_default_env['build_information'].Update(aType=BuildInfo.kBuildType, aVersion=BuildInfo.kBuildVersion)
kBuildInfo = _default_env['build_information'].BuildInformation

appAssemblyInfo = _default_env.TagReplace(_default_env.subst('$build_hardware_dir/share/LinnSetup/AssemblyInfo.cs'), 'Properties/AssemblyInfo.cs', TAGS=kBuildInfo)

files = Split("""
    Installer/NsiTemplate.txt
""")
installerResources = _default_env.Install('$variant_dir/share/Linn/LinnSetup', files)
    
files = Split("""
    Applet/BasicSetup/AppletBasicSetup.cs
    Applet/BasicSetup/BasicSetup.cs
    Applet/BasicSetup/BasicSetup.designer.cs
    Applet/Config/AppletConfig.cs
    Applet/Config/Config.cs
    Applet/Config/Config.designer.cs
    Applet/Diagnostic/AppletDiagnostic.cs
    Applet/Diagnostic/Diagnostic.cs
    Applet/Diagnostic/Diagnostic.designer.cs
    Applet/PlaybackTest/AppletPlaybackTest.cs
    Applet/PlaybackTest/PlaybackTest.cs
    Applet/PlaybackTest/PlaybackTest.designer.cs
    Applet/Presentation/AppletPresentation.cs
    Applet/Presentation/Presentation.cs
    Applet/Presentation/Presentation.designer.cs
    Applet/Reflash/AppletReflash.cs
    Applet/Reflash/Reflash.cs
    Applet/Reflash/Reflash.designer.cs
    Applet/SysLog/AppletSysLog.cs
    Applet/SysLog/SysLog.cs
    Applet/SysLog/SysLog.designer.cs
    Applet/Ticketing/AppletTicketing.cs
    Applet/Ticketing/Ticketing.cs
    Applet/Ticketing/Ticketing.designer.cs
    Applet/Applet.cs
    Applet/AppletFactory.cs
    Applet/AppletManager.cs
    Properties/Resources.Designer.cs
    ApplicationOptions.cs
    FormTree.cs
    FormTree.Designer.cs
    MainForm.cs
    MainForm.Designer.cs
    Program.cs  
    TargetMediator.cs
""")

res = _default_env.Resgen("LinnSetup.BasicSetup.resources", "Applet/BasicSetup/BasicSetup.resx")
res += _default_env.Resgen("LinnSetup.Config.resources", "Applet/Config/Config.resx")
res += _default_env.Resgen("LinnSetup.Diagnostic.resources", "Applet/Diagnostic/Diagnostic.resx")
res += _default_env.Resgen("LinnSetup.PlaybackTest.resources", "Applet/PlaybackTest/PlaybackTest.resx")
res += _default_env.Resgen("LinnSetup.Presentation.resources", "Applet/Presentation/Presentation.resx")
res += _default_env.Resgen("LinnSetup.Reflash.resources", "Applet/Reflash/Reflash.resx")
res += _default_env.Resgen("LinnSetup.SysLog.resources", "Applet/SysLog/SysLog.resx")
res += _default_env.Resgen("LinnSetup.Ticketing.resources", "Applet/Ticketing/Ticketing.resx")
res += _default_env.Resgen("LinnSetup.Properties.Resources.resources", "Properties/Resources.resx")
res += _default_env.Resgen("LinnSetup.FormTree.resources", "FormTree.resx")
res += _default_env.Resgen("LinnSetup.MainForm.resources", "MainForm.resx")

target = 'winexe'
if _default_env['variant'] == 'debug' or _default_env['variant'] == 'trace':
    target = 'exe'
    
app = _default_env.CliProgram("LinnSetup", files + appAssemblyInfo, CSCTARGET=target, CLILIBS=['OssServices', 'OssSysLib', 'OssCore', 'OssToolkitWinForms', 'OssControl', 'OssProductSupport', 'OssKinsky', 'XmlLayout', 'XmlRom', 'XmlRomCollection', 'XmlTags', 'System', 'System.Core', 'System.Data', 'System.Drawing', 'System.ServiceProcess', 'System.Web.Services', 'System.Windows.Forms', 'System.Xml'], CLIRESOURCES=res, WINICON='$variant_dir/share/Linn/Core/linn.ico', TARGETFRAMEWORKVERSION='4.0')

app.append(File(_default_env.subst('$variant_dir/share/Linn/Core/linn.ico')))
app.append(File(_default_env.subst('$variant_dir/share/Linn/ProductSupport/Tags.xml')))
app.append(File(_default_env.subst('$variant_dir/share/Linn/ProductSupport/AudioTrack.flac')))
app.append(File(_default_env.subst('$variant_dir/share/Linn/ProductSupport/Folder.jpg')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssCore.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssSysLib.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssControl.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssServices.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssDidlLite.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssKinsky.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssProductSupport.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssToolkitWinForms.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/XmlLayout.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/XmlRom.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/XmlRomCollection.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/XmlTags.dll')))
app.append(File(_default_env.subst('$install_dir/lib/ICSharpCode.SharpZipLib.dll')))
app.append(File(_default_env.subst('$install_dir/lib/taglib-sharp.dll')))
                       
installer = []
if _default_env['installers']:
    installer = _default_env.ReleaseInstallerWin32('$install_dir/share/LinnSetup', 'InstallerLinnSetup',
                        FILES      = {''             : app },
                        TEMPLATE   = _default_env.subst('$variant_dir/share/Linn/LinnSetup/NsiTemplate.txt'),
                        RESOURCES  = {'icon'    : _default_env.subst('$variant_dir/share/Linn/Core/linn.ico'),
                                      'header'  : _default_env.subst('$variant_dir/share/Linn/Core/header.bmp'),
                                      'finish'  : _default_env.subst('$variant_dir/share/Linn/Core/finish.bmp'),
                                      'license' : _default_env.subst('$variant_dir/share/Linn/Core/license.txt')},
                        PRODUCT    = 'LinnSetup',
                        VERSION      = kBuildInfo['BUILD_INFO_VERSION'],
                        LAUNCHFILE = 'LinnSetup.exe')
                        
    installer += _default_env.ReleaseInstallerDebian('$install_dir/share/LinnSetup', 'InstallerLinnSetup',
                        FILES        = {'usr/lib/LinnSetup'         : app},
                        MAINTAINER   = 'Linn [http://oss.linn.co.uk]',
                        DEPENDECIES  = 'libmono-winforms2.0-cil (>= 2.0.1), mono-gmcs (>= 2.0.1)',
                        ICON         = '$variant_dir/share/Linn/Core/linn.xpm',
                        DESCRIPTION  = 'Use this application to configure, upgrade, or diagnose problems with your Linn devices.',
                        CATEGORIES   = 'Utility;',
                        PRODUCT      = 'LinnSetup',
                        VERSION      = kBuildInfo['BUILD_INFO_VERSION'],
                        TYPE         = kBuildInfo['BUILD_INFO_TYPE'],
                        LAUNCHFILE   = 'LinnSetup.exe')
    
    installer += _default_env.ReleaseInstallerMacOsX('$install_dir/share/LinnSetup', 'InstallerLinnSetup',
                        FILES        = {''        : app},
                        ICON         = '$variant_dir/share/Linn/Core/linn.icns',
                        DESCRIPTION  = 'Use this application to configure, upgrade, or diagnose problems with your Linn devices.',
                        PRODUCT      = 'LinnSetup',
                        VERSION      = kBuildInfo['BUILD_INFO_VERSION'],
                        LAUNCHFILE   = 'LinnSetup.exe')
    Depends(installer, installerResources)

Alias('Lib', installerResources)
Alias('Lib', installer)
Alias('Test', 'Lib')
Alias('Docs')
Default(['Test','Docs'])
