//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinnTopologyDroid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ListTextColour = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Playing = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int mediaserver = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int mediaserverlist = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int room = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int roomlist = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int roomsourcelist = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int source = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int sourceimage = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int sourcelist = 2131034119;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MediaServer = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MediaServerList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Room = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RoomList = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RoomSourceList = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Source = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SourceList = 2130903047;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int mediaserverlist = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int roomlist = 2130968576;
			
			private String()
			{
			}
		}
	}
}
