Import('_default_env')

files = Split("""
    Fallback.cs
""")
if _default_env['variant'] == 'debug' or _default_env['variant'] == 'trace':
    prog = _default_env.CliProgram('Fallback', files, CLILIBS=['mscorlib', 'System', 'OssCore', 'System.Drawing', 'System.Windows.Forms'])
else:
    prog = _default_env.CliProgram('Fallback', files, CSCTARGET='winexe', CLILIBS=['mscorlib', 'System', 'OssCore', 'System.Drawing', 'System.Windows.Forms'])
Alias('Lib', prog)
