//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OssKinskyMppRadio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OssKinskyMppRadio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:output method=&quot;html&quot; doctype-system=&quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot; doctype-public=&quot;-//W3C//DTD XHTML 1.1//EN&quot;/&gt; 
        ///	&lt;xsl:param name=&quot;bg&quot;&gt;&lt;/xsl:param&gt;
        ///	&lt;xsl:param name=&quot;fg&quot;&gt;&lt;/xsl:param&gt;
        ///    &lt;xsl:param name=&quot;hibg&quot;&gt;&lt;/xsl:param&gt;
        ///    &lt;xsl:param name=&quot;hifg&quot;&gt;&lt;/xsl:param&gt;
        ///    &lt;xsl:template match=&quot;/&quot;&gt;
        ///        &lt;html&gt;
        ///	        &lt;head&gt;
        ///		        &lt;title&gt;&lt;xsl:value-of select= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ISO_3166-1_List_en xml:lang=&quot;en&quot;&gt;
        ///   &lt;ISO_3166-1_Entry&gt;
        ///      &lt;ISO_3166-1_Country_name&gt;AFGHANISTAN&lt;/ISO_3166-1_Country_name&gt;
        ///      &lt;ISO_3166-1_Alpha-2_Code_element&gt;AF&lt;/ISO_3166-1_Alpha-2_Code_element&gt;
        ///   &lt;/ISO_3166-1_Entry&gt;
        ///   &lt;ISO_3166-1_Entry&gt;
        ///      &lt;ISO_3166-1_Country_name&gt;ÅLAND ISLANDS&lt;/ISO_3166-1_Country_name&gt;
        ///      &lt;ISO_3166-1_Alpha-2_Code_element&gt;AX&lt;/ISO_3166-1_Alpha-2_Code_element&gt;
        ///   &lt;/ISO_3166-1_Entry&gt;
        ///   &lt;ISO_3166-1_Entry&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string iso_3166_1_list_en {
            get {
                return ResourceManager.GetString("iso_3166_1_list_en", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Radio {
            get {
                object obj = ResourceManager.GetObject("Radio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RadioActive {
            get {
                object obj = ResourceManager.GetObject("RadioActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
