// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KinskyTouch {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("CellBrowserHeaderFactory")]
	public partial class CellBrowserHeaderFactory {
		
		private CellBrowserHeader __mt_cellBrowserHeader;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("cellBrowserHeader")]
		private CellBrowserHeader cellBrowserHeader {
			get {
				this.__mt_cellBrowserHeader = ((CellBrowserHeader)(this.GetNativeField("cellBrowserHeader")));
				return this.__mt_cellBrowserHeader;
			}
			set {
				this.__mt_cellBrowserHeader = value;
				this.SetNativeField("cellBrowserHeader", value);
			}
		}
	}
	
	// Base type probably should be MonoTouch.UIKit.UITableViewCell or subclass
	[MonoTouch.Foundation.Register("CellBrowserHeader")]
	public partial class CellBrowserHeader {
		
		private MonoTouch.UIKit.UIImageView __mt_imageViewArtwork;
		
		private MonoTouch.UIKit.UILabel __mt_labelTitle;
		
		private MonoTouch.UIKit.UILabel __mt_labelArtistAlbum;
		
		private MonoTouch.UIKit.UILabel __mt_labelComposer;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("imageViewArtwork")]
		private MonoTouch.UIKit.UIImageView imageViewArtwork {
			get {
				this.__mt_imageViewArtwork = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageViewArtwork")));
				return this.__mt_imageViewArtwork;
			}
			set {
				this.__mt_imageViewArtwork = value;
				this.SetNativeField("imageViewArtwork", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelTitle")]
		private MonoTouch.UIKit.UILabel labelTitle {
			get {
				this.__mt_labelTitle = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelTitle")));
				return this.__mt_labelTitle;
			}
			set {
				this.__mt_labelTitle = value;
				this.SetNativeField("labelTitle", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelArtistAlbum")]
		private MonoTouch.UIKit.UILabel labelArtistAlbum {
			get {
				this.__mt_labelArtistAlbum = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelArtistAlbum")));
				return this.__mt_labelArtistAlbum;
			}
			set {
				this.__mt_labelArtistAlbum = value;
				this.SetNativeField("labelArtistAlbum", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelComposer")]
		private MonoTouch.UIKit.UILabel labelComposer {
			get {
				this.__mt_labelComposer = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelComposer")));
				return this.__mt_labelComposer;
			}
			set {
				this.__mt_labelComposer = value;
				this.SetNativeField("labelComposer", value);
			}
		}
	}
}
