// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KinskyTouch {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("CellBrowserItemFactory")]
	public partial class CellBrowserItemFactory {
		
		private CellBrowserItem __mt_cellBrowserItem;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("cellBrowserItem")]
		private CellBrowserItem cellBrowserItem {
			get {
				this.__mt_cellBrowserItem = ((CellBrowserItem)(this.GetNativeField("cellBrowserItem")));
				return this.__mt_cellBrowserItem;
			}
			set {
				this.__mt_cellBrowserItem = value;
				this.SetNativeField("cellBrowserItem", value);
			}
		}
	}
	
	// Base type probably should be MonoTouch.UIKit.UITableViewCell or subclass
	[MonoTouch.Foundation.Register("CellBrowserItem")]
	public partial class CellBrowserItem {
		
		private MonoTouch.UIKit.UILabel __mt_labelTitle;
		
		private MonoTouch.UIKit.UILabel __mt_labelArtistAlbum;
		
		private MonoTouch.UIKit.UILabel __mt_labelDurationBitrate;
		
		private MonoTouch.UIKit.UILabel __mt_labelTrackNumber;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("labelTitle")]
		private MonoTouch.UIKit.UILabel labelTitle {
			get {
				this.__mt_labelTitle = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelTitle")));
				return this.__mt_labelTitle;
			}
			set {
				this.__mt_labelTitle = value;
				this.SetNativeField("labelTitle", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelArtistAlbum")]
		private MonoTouch.UIKit.UILabel labelArtistAlbum {
			get {
				this.__mt_labelArtistAlbum = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelArtistAlbum")));
				return this.__mt_labelArtistAlbum;
			}
			set {
				this.__mt_labelArtistAlbum = value;
				this.SetNativeField("labelArtistAlbum", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelDurationBitrate")]
		private MonoTouch.UIKit.UILabel labelDurationBitrate {
			get {
				this.__mt_labelDurationBitrate = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelDurationBitrate")));
				return this.__mt_labelDurationBitrate;
			}
			set {
				this.__mt_labelDurationBitrate = value;
				this.SetNativeField("labelDurationBitrate", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelTrackNumber")]
		private MonoTouch.UIKit.UILabel labelTrackNumber {
			get {
				this.__mt_labelTrackNumber = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelTrackNumber")));
				return this.__mt_labelTrackNumber;
			}
			set {
				this.__mt_labelTrackNumber = value;
				this.SetNativeField("labelTrackNumber", value);
			}
		}
	}
}
