Import('_default_env')

if _default_env['hardware'] == 'Windows':
    SConscript('Windows/SConscript', exports = ['_default_env'])
elif _default_env['hardware'] == 'MacOsX':
    SConscript('MacOsX/SConscript', exports = ['_default_env'])
elif _default_env['hardware'] == 'Ios':
    SConscript('Ios/SConscript', exports = ['_default_env'])
elif  _default_env['hardware'] == 'Linux':
    SConscript('Linux/SConscript', exports = ['_default_env'])

