Import('_default_env')

import BuildInfo

_default_env['build_information'].Update(aType=BuildInfo.kBuildType, aVersion=BuildInfo.kBuildVersion)
kBuildInfo = _default_env['build_information'].BuildInformation

SConscript('Linn/Songcast/SConscript', exports = ['_default_env', 'kBuildInfo'])

Alias('Test', 'Lib')
Alias('Docs')
Default(['Test','Docs'])
