Import('_default_env')

import BuildInfo

_default_env['build_information'].Update(aType=BuildInfo.kBuildType, aVersion=BuildInfo.kBuildVersion)
kBuildInfo = _default_env['build_information'].BuildInformation

appAssemblyInfo = _default_env.TagReplace(_default_env.subst('$build_hardware_dir/share/KinskyJukebox/AssemblyInfo.cs'), 'Properties/AssemblyInfo.cs', TAGS=kBuildInfo)

files = Split("""
    Installer/Header.bmp
    Installer/NsiTemplate.txt
""")
installerResources = _default_env.Install('$variant_dir/share/Linn/KinskyJukebox', files)

files = Split("""
    Properties/Resources.Designer.cs
    ApplicationOptions.cs
    FormDevices.cs
    FormDevices.Designer.cs
    FormKinskyJukebox.cs
    FormKinskyJukebox.Designer.cs
    FormPrint.cs
    FormPrint.Designer.cs
    FormTrackMetadata.cs
    FormTrackMetadata.Designer.cs
    FormUpdate.cs
    FormUpdate.Designer.cs
    FormWizard.cs
    FormWizard.Designer.cs
    GetMedia.cs
    OptionPageOrganisation.cs
    OptionPageSetup.cs
    OptionPageWizard.cs
    Presets.cs
    Program.cs
""")

res  = _default_env.Resgen('KinskyJukebox.Properties.Resources.resources', 'Properties/Resources.resx')
res += _default_env.Resgen('KinskyJukebox.FormDevices.resources', 'FormDevices.resx')
res += _default_env.Resgen('KinskyJukebox.FormKinskyJukebox.resources', 'FormKinskyJukebox.resx')
res += _default_env.Resgen('KinskyJukebox.FormPrint.resources', 'FormPrint.resx')
res += _default_env.Resgen('KinskyJukebox.FormTrackMetadata.resources', 'FormTrackMetadata.resx')
res += _default_env.Resgen('KinskyJukebox.FormUpdate.resources', 'FormUpdate.resx')
res += _default_env.Resgen('KinskyJukebox.FormWizard.resources', 'FormWizard.resx')

target = 'winexe'
if _default_env['variant'] == 'debug' or _default_env['variant'] == 'trace':
    target = 'exe'
    
progAssembly = _default_env.CliProgram('KinskyJukebox', files + appAssemblyInfo, CSCTARGET=target, CLILIBS=['OssCore', 'OssToolkitWinForms', 'OssSysLib', 'OssControl', 'OssServices', 'OssDidlLite', 'OssProductSupport', 'OssKinsky', 'System.Data', 'System.Drawing', 'System.Windows.Forms', 'itextsharp', 'taglib-sharp', 'policy.2.0.taglib-sharp'], CLIRESOURCES=res, WINICON='$variant_dir/share/Linn/Kinsky/Kinsky.ico', TARGETFRAMEWORKVERSION='4.0')

reqAssemblies = []
reqAssemblies.extend(Split("""
    OssCore
    OssToolkitWinForms
    OssSysLib
    OssControl
    OssServices
    OssDidlLite
    OssProductSupport
    OssKinsky
    taglib-sharp
    itextsharp
    policy.2.0.taglib-sharp
"""))

app = progAssembly
app.append(File(_default_env.subst('$variant_dir/share/Linn/Kinsky/Kinsky.ico')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssCore.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssToolkitWinForms.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssSysLib.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssControl.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssServices.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssDidlLite.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssProductSupport.dll')))
app.append(File(_default_env.subst('$install_dir/lib/Linn/OssKinsky.dll')))
app.append(File(_default_env.subst('$install_dir/lib/taglib-sharp.dll')))
app.append(File(_default_env.subst('$install_dir/lib/itextsharp.dll')))
app.append(File(_default_env.subst('$install_dir/lib/policy.2.0.taglib-sharp.dll')))
app.append(File(_default_env.subst('$install_dir/lib/policy.2.0.taglib-sharp.config')))

installer = []
if _default_env['installers']:
    installer = []
    if _default_env['hardware'] == 'Windows':
        installer += _default_env.ReleaseInstallerWin32('$install_dir/share/KinskyJukebox', 'InstallerKinskyJukebox',
                            FILES        = {''        : app},
                            TEMPLATE     = _default_env.subst('$variant_dir/share/Linn/KinskyJukebox/NsiTemplate.txt'),
                            RESOURCES    = {'icon'    : _default_env.subst('$variant_dir/share/Linn/Kinsky/Kinsky.ico'),
                                            'header'  : _default_env.subst('$variant_dir/share/Linn/KinskyJukebox/Header.bmp'),
                                            'finish'  : _default_env.subst('$variant_dir/share/Linn/Kinsky/finish.bmp'),
                                            'license' : _default_env.subst('$variant_dir/share/Linn/Core/license.txt')},
                            PRODUCT      = 'KinskyJukebox',
                            VERSION      = kBuildInfo['BUILD_INFO_VERSION'],
                            LAUNCHFILE   = 'KinskyJukebox.exe')
    if _default_env['hardware'] == 'Linux':
        installer += _default_env.ReleaseInstallerDebian('$install_dir/share/KinskyJukebox', 'InstallerKinskyJukebox',
                            FILES        = {'usr/lib/KinskyJukebox'         : app},
                            MAINTAINER   = 'Linn [http://oss.linn.co.uk]',
                            DEPENDECIES  = 'libmono-winforms2.0-cil (>= 2.0.1), mono-gmcs (>= 2.0.1)',
                            ICON         = '$variant_dir/share/Linn/Kinsky/KinskyJukebox.xpm',
                            DESCRIPTION  = 'Manages playlists and presets for the Linn Jukebox service.',
                            CATEGORIES   = 'Utility;',
                            PRODUCT      = 'KinskyJukebox',
                            VERSION      = kBuildInfo['BUILD_INFO_VERSION'],
                            TYPE         = kBuildInfo['BUILD_INFO_TYPE'],
                            LAUNCHFILE   = 'KinskyJukebox.exe')

    if _default_env['hardware'] == 'MacOsX':
        # build the Mac OSX .app bundle and .pkg installer and install them
        installer += _default_env.ReleaseInstallerMacOsXWithMono('InstallerKinskyJukebox', progAssembly,
                            APPNAME = 'KinskyJukebox',
                            APPINSTFOLDER = '$install_dir/bin',
                            PKGINSTFOLDER = '$install_dir/share/KinskyJukebox',
                            APPCERT = '"Developer ID Application: Linn Products Ltd"',
                            PKGCERT = '"Developer ID Installer: Linn Products Ltd"',
                            CLILIBS = reqAssemblies,
                            RESOURCES = { '' : [ File(_default_env.subst('$variant_dir/share/Linn/Kinsky/Kinsky.ico')) ] },
                            EXERESOURCES = { '' : [ File(_default_env.subst('$install_dir/lib/policy.2.0.taglib-sharp.config')) ] },
                            ICON = '$variant_dir/share/Linn/Kinsky/Kinsky.icns',
                            VERSION = kBuildInfo['BUILD_INFO_VERSION'])
    Depends(installer, installerResources)

Alias('Lib', installerResources)
Alias('Lib', installer)
Alias('Test', 'Lib')
Alias('Docs')
Default(['Test','Docs'])

