Import('_default_env')

# KinskyMedia Library

files = Split("""
	AssemblyInfo.cs
    KinskyMedia.cs
    Database/Database.cs
    Database/DatabaseDb4o.cs
	Scanner/Scanner.cs
	Scanner/ScannerTagLib.cs
	Scanner/Luminescence.Xiph/Enums.cs
	Scanner/Luminescence.Xiph/ExtensionMethods.cs
	Scanner/Luminescence.Xiph/FlacTagger.cs
	Scanner/Luminescence.Xiph/Genre.cs
	Scanner/Luminescence.Xiph/ID3PictureFrame.cs
	Scanner/Luminescence.Xiph/OggPage.cs
	Scanner/Luminescence.Xiph/OggPageReader.cs
	Scanner/Luminescence.Xiph/OggTagger.cs
	Scanner/Luminescence.Xiph/VorbisComment.cs
""")

prog = _default_env.CliProgram('SneakyMedia', files, CLILIBS=['taglib-sharp.dll', 'policy.2.0.taglib-sharp.dll', 'Db4objects.Db4o.dll', 'System.Data.dll'])

Alias('Lib', prog)
Alias('Test', 'Lib')

Default('Test')

