Import('_default_env')

file = _default_env.Install('$install_dir/bin/Test', 'TestSceneGraph.py')
py1 = _default_env.AddPostAction(file, Chmod(file, 0755))
Alias('TestSceneGraph', py1)
file = _default_env.Install('$install_dir/bin/Test', 'TestSrt.py')
py2 = _default_env.AddPostAction(file, Chmod(file, 0755))
Alias('TestSrt', py2)

files = Split("""
    TestFiles/Test1.xml
    TestFiles/Test2.xml
    TestFiles/Test3.xml
    TestFiles/TestPackage.xml
    TestFiles/TestPackage2.xml
    TestFiles/TestWidgets.xml
""")
testFiles = _default_env.Install( '$install_dir/share/Linn/Test/Gui', files )
file = _default_env.Install('$install_dir/bin/Test', 'TestGuiLayout.py')
py3 = _default_env.AddPostAction(file, Chmod(file, 0755))
Alias('TestGuiLayout', py3)
Depends(py3, testFiles)

file = _default_env.Install('$install_dir/bin/Test', 'TestSceneGraphEvent.py')
py4 = _default_env.AddPostAction(file, Chmod(file, 0755))
Alias('TestSceneGraphEvent', py4)

py = py1 + py2 + py3 + py4
Alias('Test', py)

if _default_env['hardware'] != 'PocketPc':
    #test  = CliProgram( 'Test/TestGui', 'TestGui.cs', CILLIBS=['System.Windows.Forms', 'System.Drawing'] )
    test = _default_env.CliProgram( 'Test/TestSceneGraph', 'TestSceneGraph.cs', CLILIBS=['mscorlib', 'OssTestFramework', 'OssGui'])
    test += _default_env.CliProgram( 'Test/TestSrt', 'TestSrt.cs', CLILIBS=['mscorlib', 'OssTestFramework', 'OssGui'])
    test += _default_env.CliProgram( 'Test/TestPackage', 'TestPackage.cs', CLILIBS=['mscorlib', 'OssTestFramework', 'OssGui', 'OssCore'])
    test += _default_env.CliProgram( 'Test/TestSceneGraphEvent', 'TestSceneGraphEvent.cs', CLILIBS=['mscorlib', 'OssTestFramework', 'OssGui', 'OssCore'])
    test += _default_env.CliProgram( 'Test/TestGuiLayout', 'TestGuiLayout.cs', CLILIBS=['mscorlib', 'OssTestFramework', 'OssGui', 'OssCore', 'System.Xml', 'System.Drawing'])
    test += _default_env.CliProgram( 'Test/TestWidgets', 'TestWidgets.cs', CLILIBS=['mscorlib', 'OssTestFramework', 'OssGui', 'OssCore', 'System', 'System.Windows.Forms', 'System.Drawing'])
    test += _default_env.CliProgram( 'Test/TestMultiplePackages', 'TestMultiplePackages.cs', CLILIBS=['mscorlib', 'OssTestFramework', 'OssGui', 'OssCore', 'System', 'System.Windows.Forms', 'System.Drawing'])
    test += _default_env.CliProgram( 'Test/TestNodeInput', 'TestNodeInput.cs', CLILIBS=['mscorlib', 'OssTestFramework','OssGui', 'OssCore'])
    #test += _default_env.CliProgram( 'Test/TestNodeList', 'TestNodeList.cs', CLILIBS=['mscorlib', 'OssTestFramework','OssGui', 'OssCore'])
    test += _default_env.CliProgram( 'Test/TestListCache', 'TestListCache.cs', CLILIBS=['mscorlib', 'OssTestFramework','OssGui', 'OssCore'])
    test += _default_env.CliProgram( 'Test/TestEditorTranslatorList', 'TestEditorTranslatorList.cs', CLILIBS=['mscorlib', 'OssTestFramework','OssGui', 'OssCore'])
    test += _default_env.CliProgram( 'Test/TestPackageManager', 'TestPackageManager.cs', CLILIBS=['mscorlib', 'OssTestFramework', 'OssGui', 'OssCore'])
    test += _default_env.CliProgram( 'Test/TestTextureManager', 'TestTextureManager.cs', CLILIBS=['mscorlib', 'OssTestFramework', 'OssGui', 'OssCore'])
    test += _default_env.CliProgram( 'Test/TestRender', 'TestRender.cs', CLILIBS=['mscorlib', 'OssGui', 'OssCore', 'System.Windows.Forms', 'System', 'System.Drawing'])
    test += _default_env.CliProgram( 'Test/TestMouseMove', 'TestMouseMove.cs', CLILIBS=['mscorlib', 'System', 'System.Windows.Forms', 'System.Drawing'])
    Depends(test, testFiles)
    Alias('Test', test)

#files = Split("""
#    TestWibbler/Bitmaps/Background1.bmp
#    TestWibbler/Bitmaps/Background2.bmp
#    TestWibbler/Bitmaps/Exit.png
#    TestWibbler/Bitmaps/FocusOff1.png
#    TestWibbler/Bitmaps/FocusOff2.png
#    TestWibbler/Bitmaps/FocusOn1.png
#    TestWibbler/Bitmaps/FocusOn2.png
#    TestWibbler/Bitmaps/Wheel.png
#""")
#images = _default_env.Install('$install_dir/share/Linn/Gui/Test/Wibbler/Bitmaps', files)
#layout = _default_env.Install('$install_dir/share/Linn/Gui/Test/Wibbler', 'TestWibbler/TestWibbler1.xml')
#layout += _default_env.Install('$install_dir/share/Linn/Gui/Test/Wibbler', 'TestWibbler/TestWibbler2.xml')
#package = _default_env.Install('$install_dir/share/Linn/Gui', 'TestWibbler/TestWibblerPackage.xml')
#list = _default_env.Install('$install_dir/share/Linn/Gui/Test/Wibbler', 'TestWibbler/ExampleList.xml')
#prog = _default_env.CliProgram( 'Test/TestWibbler1', 'TestWibbler/TestWibbler1.cs', CLILIBS=['OssTestFramework', 'OssGui', 'OssCore', 'System.Windows.Forms', 'System.Drawing'])
#prog += _default_env.CliProgram( 'Test/TestWibbler2', 'TestWibbler/TestWibbler2.cs', CLILIBS=['OssTestFramework', 'OssGui', 'OssCore', 'System.Windows.Forms', 'System.Drawing'])
#Depends(prog, layout + images + package + list)
#Depends(prog, 'Gui')


#files = Split("""
#    WibblerPrototype/Bitmaps/Background.png
#    WibblerPrototype/Bitmaps/Exit.png
#    WibblerPrototype/Bitmaps/Wibbler.png
#""")
#images = _default_env.Install('$install_dir/share/Linn/Gui/Prototype/Wibbler/Bitmaps', files)
#layout = _default_env.Install('$install_dir/share/Linn/Gui/Prototype/Wibbler', 'WibblerPrototype/WibblerPrototype.xml')
#package = _default_env.Install('$install_dir/share/Linn/Gui', 'WibblerPrototype/WibblerPrototypePackage.xml')
#prototype = _default_env.CliProgram( 'Test/WibblerPrototype', 'WibblerPrototype/WibblerPrototype.cs', LINNCILLIBS=['TestFramework', 'Gui', 'Core'], CILLIBS=['System.Windows.Forms', 'System.Drawing'])
#Depends(prototype, layout + images + package)
#Depends(prototype, 'Gui')

#layout = _default_env.Install('$install_dir/share/Linn/Gui/TestListWidget', 'TestListWidget/TestListWidget.xml')
#package = _default_env.Install('$install_dir/share/Linn/Gui', 'TestListWidget/TestListWidgetPackage.xml')
#prototype = _default_env.CliProgram( 'Test/TestListWidgetInter', 'TestListWidget/TestListWidgetInter.cs', LINNCILLIBS=['TestFramework', 'Gui', 'Core'], CILLIBS=['System.Windows.Forms', 'System.Drawing'])
#Depends(prototype, layout + package)
#Depends(prototype, 'Gui')

