Import('_default_env')

kVersion = 'development'

files = Split("""
    ProntoScripts/build/KinskyPronto.exe
""")
installers  = _default_env.Install('$variant_dir/share/KinskyPronto', files)

Alias('Lib', installers)
Alias('Test', 'Lib')

Default('Test')

