// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KinskyTouch {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("CellBrowserFactory")]
	public partial class CellBrowserFactory {
		
		private CellBrowser __mt_cellBrowser;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("cellBrowser")]
		private CellBrowser cellBrowser {
			get {
				this.__mt_cellBrowser = ((CellBrowser)(this.GetNativeField("cellBrowser")));
				return this.__mt_cellBrowser;
			}
			set {
				this.__mt_cellBrowser = value;
				this.SetNativeField("cellBrowser", value);
			}
		}
	}
	
	// Base type probably should be MonoTouch.UIKit.UITableViewCell or subclass
	[MonoTouch.Foundation.Register("CellBrowser")]
	public partial class CellBrowser {
		
		private MonoTouch.UIKit.UIImageView __mt_imageViewArtwork;
		
		private MonoTouch.UIKit.UILabel __mt_labelTitle;
		
		private MonoTouch.UIKit.UILabel __mt_labelArtistAlbum;
		
		private MonoTouch.UIKit.UILabel __mt_labelDurationBitrate;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("imageViewArtwork")]
		private MonoTouch.UIKit.UIImageView imageViewArtwork {
			get {
				this.__mt_imageViewArtwork = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("imageViewArtwork")));
				return this.__mt_imageViewArtwork;
			}
			set {
				this.__mt_imageViewArtwork = value;
				this.SetNativeField("imageViewArtwork", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelTitle")]
		private MonoTouch.UIKit.UILabel labelTitle {
			get {
				this.__mt_labelTitle = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelTitle")));
				return this.__mt_labelTitle;
			}
			set {
				this.__mt_labelTitle = value;
				this.SetNativeField("labelTitle", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelArtistAlbum")]
		private MonoTouch.UIKit.UILabel labelArtistAlbum {
			get {
				this.__mt_labelArtistAlbum = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelArtistAlbum")));
				return this.__mt_labelArtistAlbum;
			}
			set {
				this.__mt_labelArtistAlbum = value;
				this.SetNativeField("labelArtistAlbum", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelDurationBitrate")]
		private MonoTouch.UIKit.UILabel labelDurationBitrate {
			get {
				this.__mt_labelDurationBitrate = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelDurationBitrate")));
				return this.__mt_labelDurationBitrate;
			}
			set {
				this.__mt_labelDurationBitrate = value;
				this.SetNativeField("labelDurationBitrate", value);
			}
		}
	}
}
