Import('_default_env kBuildInfo appAssemblyInfo')

nib  = _default_env.IbTool('ArtworkTileView', 'ArtworkTileView.xib')
nib += _default_env.IbTool('CellBrowser', 'CellBrowser.xib')
nib += _default_env.IbTool('CellBrowserHeader', 'CellBrowserHeader.xib')
nib += _default_env.IbTool('CellBrowserItem', 'CellBrowserItem.xib')
nib += _default_env.IbTool('CellDefault', 'CellDefault.xib')
nib += _default_env.IbTool('CellPlaylist', 'CellPlaylist.xib')
nib += _default_env.IbTool('CellPlaylistItem', 'CellPlaylistItem.xib')
nib += _default_env.IbTool('CellSender', 'CellSender.xib')
nib += _default_env.IbTool('MainWindowIpad', 'MainWindowIpad.xib')
nib += _default_env.IbTool('MainWindowIphone', 'MainWindowIphone.xib')
nib += _default_env.IbTool('SaveDialog', 'SaveDialog.xib')
nib += _default_env.IbTool('TimeButtons', 'TimeButtons.xib')
nib += _default_env.IbTool('TimeRotary', 'TimeRotary.xib')
nib += _default_env.IbTool('VolumeButtons', 'VolumeButtons.xib')
nib += _default_env.IbTool('VolumeRotary', 'VolumeRotary.xib')
nib += _default_env.IbTool('CellLazyLoadDefault', 'CellLazyLoadDefault.xib')
nib += _default_env.IbTool('CellRoom', 'CellRoom.xib')

res = Split("""
    KinskyLogoAbout.png
    Resources/Default-Landscape.png
    Resources/Default-Landscape@2x.png
    Resources/Default-Portrait.png
    Resources/Default-Portrait@2x.png
    Resources/Default~iphone.png
    Resources/Default@2x~iphone.png
    Resources/Default-568h@2x~iphone.png
    Resources/KinskyLogoIphone.png
    Resources/KinskyLogoSpotlightIphone.png
    Resources/KinskyLogoIpad.png
    Resources/KinskyLogoSpotlightIpad.png
    Resources/KinskyLogoIphone4.png
    Resources/KinskyLogoSpotlightIphone4.png
    Resources/KinskyLogoIpad3.png
    Resources/KinskyLogoSpotlightIpad3.png
""")

layoutRes = Split("""
    $variant_dir/share/Linn/Resources/Kinsky2/Images/ClockIcon.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/ClockIconElapsed.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/ClockIconRemaining.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/MuteIcon.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/Mute.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/MuteActive.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/LeftFiller.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/TopRightEdge.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/TopLeftEdge.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/TopFiller.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/BottomLeftEdge.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/BottomRightEdge.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/BottomFiller.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/Button.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/FfwdButton.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/FrwdButton.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/RightFiller.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/SkipBack.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/SkipBackDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/SkipForward.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/SkipForwardDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/Pause.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/Play.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/Stop.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/Array.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/PauseOver.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/PlayOver.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/StopOver.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/Wheel.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/WheelLarge.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/WheelLargeOver.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/Screws.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/ScrewsLarge.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/WheelOver.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/Rocker.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/RockerLeftDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/RockerRightDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/WheelMute.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Shuffle.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/ShuffleDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/ShuffleOn.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/ShuffleOnDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/PauseDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/PlayDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/StopDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/SkipBackOver.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/SkipForwardOver.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Repeat.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/RepeatDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/RepeatOn.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/RepeatOnDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/RoomSource.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/LinnLogo.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/TramLines.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Home.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/HomeDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/HourGlass.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/HourGlass2.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/List.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Settings.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Delete.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/DeleteDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Save.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/SaveDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Standby.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/StandbyDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/StandbyOn.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Multi.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/MultiDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/MultiOnDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/StandbyOnDown.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/HomeOn.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/MultiOn.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Album.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/AlbumArtError.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Artist.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Directory.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/DisclosureIndicator.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Error.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Folder.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Library.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Loading.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Playing.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Playlist.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/PlaylistItem.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/PlaylistSource.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/CD.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Radio.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Room.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Source.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Sender.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/SenderNoSend.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Track.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/UPNP.png
    $variant_dir/share/Linn/Resources/Kinsky2/Icons/Video.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/UIBarButton.png
    $variant_dir/share/Linn/Resources/Kinsky2/Images/UIBarButtonIPhone.png
""")

res += [_default_env.subst(r) for r in layoutRes]

itunes_res = Split("""
	Installer/iTunesArtwork
	Installer/iTunesMetadata.plist
""")

files = Split("""
    AppDelegate.cs
    AppDelegateIpad.cs
    AppDelegateIphone.cs
    AppRestartHandler.cs
    ArtworkCache.cs
    ArtworkTileView.cs
    ArtworkTileView.xib.designer.cs
    BrowserToolbar.cs
    CellLazyLoadDefault.cs
    CellLazyLoadDefault.xib.designer.cs
    CellBrowser.cs
    CellBrowser.xib.designer.cs
    CellBrowserHeader.cs
    CellBrowserHeader.xib.designer.cs
    CellBrowserItem.cs
    CellBrowserItem.xib.designer.cs
    CellDefault.cs
    CellDefault.xib.designer.cs
    CellLazyLoadImage.cs
    CellPlaylist.cs
    CellPlaylist.xib.designer.cs
    CellPlaylistItem.cs
    CellPlaylistItem.xib.designer.cs
    CellRoom.cs
    CellRoom.xib.designer.cs
    CellSender.cs
    CellSender.xib.designer.cs
    ConfigController.cs
    HelperKinskyTouch.cs
    Main.cs
    MainWindowIpad.xib.designer.cs
    MainWindowIphone.xib.designer.cs
    MediaProviderSupport.cs
    OptionInsertMode.cs
    OptionPageGeneral.cs
    Reachability.cs
    ResourceManager.cs
    SaveDialog.xib.designer.cs
    SaveViewController.cs
    SourceToolbar.cs
    TimeButtons.xib.designer.cs
    TimeController.cs
    TimeRotary.xib.designer.cs
    UIControlRotary.cs
    UIViewControllerKinskyTouch.cs
    UIViewInfo.cs
    Views.cs
    ViewWidgetBrowser.cs
    ViewWidgetButtons.cs
    ViewWidgetPlaylist.cs
    ViewWidgetSelectors.cs
    ViewWidgetSenderReceiver.cs
    ViewWidgetTime.cs
    ViewWidgetTrack.cs
    ViewWidgetVolume.cs
    VolumeButtons.xib.designer.cs
    VolumeController.cs
    VolumeRotary.xib.designer.cs
""")

files += appAssemblyInfo

rootResources = [File(f) for f in res]
rootResources += [File(f) for f in nib]
resources = {'' : rootResources}

prog = _default_env.CliProgram('Kinsky', files, CLILIBPATH=['$CLILIBPATH', '$install_dir/lib/Linn/Plugins/Bbc', '$install_dir/lib/Linn/Plugins/MovieTrailers', '$install_dir/lib/Linn/Plugins/Wfmu'], CLILIBS=['OssCore', 'OssToolkitIos', 'OssControl', 'OssDidlLite', 'OssTopology', 'OssKinsky', 'monotouch'])#, 'OssKinskyMppBbc', 'OssKinskyMppMovieTrailers', 'OssKinskyMppWfmu'])
Depends(prog, nib)

bundle = _default_env.ReleaseInstallerIos('$install_dir/share/Kinsky/Development', prog,
                                          CLILIBS = ['OssCore', 'OssToolkitIos', 'OssControl', 'OssDidlLite', 'OssTopology', 'OssKinsky', 'monotouch'],#, '$install_dir/lib/Linn/Plugins/Bbc/OssKinskyMppBbc', '$install_dir/lib/Linn/Plugins/MovieTrailers/OssKinskyMppMovieTrailers', '$install_dir/lib/Linn/Plugins/Wfmu/OssKinskyMppWfmu'],
                                          RESOURCES = resources,
                                          ITUNESRESOURCES = itunes_res,
                                          PRODUCT         = 'Kinsky',
                                          BUNDLEID        = 'KinskyTouch',
                                          VERSION      	  = kBuildInfo['BUILD_INFO_VERSION'],
                                          TYPE      	  = kBuildInfo['BUILD_INFO_TYPE'],
                                          IDENTITY        = "iPhone Developer: Keith Robertson (N5FMX5CWP6)",
                                          PROFILE         = "KinskyTouch")

if _default_env['variant'] == 'release':
    bundle += _default_env.ReleaseInstallerIos('$install_dir/share/Kinsky/AdHoc', prog,
                                               CLILIBS = ['OssCore', 'OssToolkitIos', 'OssControl', 'OssDidlLite', 'OssTopology', 'OssKinsky', 'monotouch'],#, '$install_dir/lib/Linn/Plugins/Bbc/OssKinskyMppBbc', '$install_dir/lib/Linn/Plugins/MovieTrailers/OssKinskyMppMovieTrailers', '$install_dir/lib/Linn/Plugins/Wfmu/OssKinskyMppWfmu'],
                                               RESOURCES = resources,
                                               ITUNESRESOURCES = itunes_res,
                                               PRODUCT         = 'Kinsky',
                                               BUNDLEID        = 'KinskyTouch',
                                               VERSION         = kBuildInfo['BUILD_INFO_VERSION'],
                                               TYPE            = kBuildInfo['BUILD_INFO_TYPE'],
                                               IDENTITY        = "iPhone Distribution: Linn Products Ltd",
                                               PROFILE         = "Kinsky Ad Hoc")
	                                          
    bundle += _default_env.ReleaseInstallerIos('$install_dir/share/Kinsky/AppStore', prog,
                                               CLILIBS = ['OssCore', 'OssToolkitIos', 'OssControl', 'OssDidlLite', 'OssTopology', 'OssKinsky', 'monotouch'],#, '$install_dir/lib/Linn/Plugins/Bbc/OssKinskyMppBbc', '$install_dir/lib/Linn/Plugins/MovieTrailers/OssKinskyMppMovieTrailers', '$install_dir/lib/Linn/Plugins/Wfmu/OssKinskyMppWfmu'],
                                               RESOURCES = resources,
                                               ITUNESRESOURCES = itunes_res,
                                               PRODUCT         = 'Kinsky',
                                               BUNDLEID        = 'KinskyTouch',
                                               VERSION         = kBuildInfo['BUILD_INFO_VERSION'],
                                               TYPE            = kBuildInfo['BUILD_INFO_TYPE'],
                                               IDENTITY        = "iPhone Distribution: Linn Products Ltd",
                                               PROFILE         = "Kinsky App Store")

Alias('Lib', bundle)
Alias('Test', 'Lib')

Default('Test')
