// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KinskyTouch {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ViewWidgetTimeButtons")]
	public partial class ViewWidgetTimeButtons {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_buttonTime;
		
		private MonoTouch.UIKit.UIButton __mt_buttonFfwd;
		
		private MonoTouch.UIKit.UIButton __mt_buttonFrwd;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonTime")]
		private MonoTouch.UIKit.UIButton buttonTime {
			get {
				this.__mt_buttonTime = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonTime")));
				return this.__mt_buttonTime;
			}
			set {
				this.__mt_buttonTime = value;
				this.SetNativeField("buttonTime", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonFfwd")]
		private MonoTouch.UIKit.UIButton buttonFfwd {
			get {
				this.__mt_buttonFfwd = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonFfwd")));
				return this.__mt_buttonFfwd;
			}
			set {
				this.__mt_buttonFfwd = value;
				this.SetNativeField("buttonFfwd", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonFrwd")]
		private MonoTouch.UIKit.UIButton buttonFrwd {
			get {
				this.__mt_buttonFrwd = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonFrwd")));
				return this.__mt_buttonFrwd;
			}
			set {
				this.__mt_buttonFrwd = value;
				this.SetNativeField("buttonFrwd", value);
			}
		}
	}
}
