(_default_env, _tool_env) = SConscript('../BuildSystem/Initialise.py')
import os
_default_env.SConsignFile('$sconsign_dir/.sconsign.$hardware-$variant')
_default_env['build_dir'] += '/' + os.path.split(os.getcwd())[1]
_tool_env['build_dir'] = _default_env['build_dir']
SConscript('SConscript', variant_dir = _default_env['build_dir'], duplicate = 0, exports = ['_default_env', '_tool_env'])
